### PR TITLE
github: add a CI workflow

### PR DESCRIPTION
**Pull request by woodruffw**
My attempt at #60.

I'm not too familiar with Go's build (still), so this might take a little bit of futzing before it passes.

### CODE REVIEW

**Comment by woodruffw** [comment]
Testing the CI on my own fork, and it seems to be working well: https://github.com/woodruffw-forks/gllvm/pull/1

**Comment by woodruffw** [comment]
I also went ahead and deleted the old Travis CI configuration, in a separate commit. Let me know if that's premature and I can revert it.

**Comment by ianamason** [comment]
Sorry I have been busy. I'm not ignoring you. I will look at this SOON.

**Comment by ianamason** [comment]
Ooops wrong button :-(

**Comment by woodruffw** [comment]
Anything else I can do to push this along? 🙂

**Comment by ianamason** [comment]
Nagging me seems the right way to go. Lets just be brave and see what breaks.

**Pull request merged**
